root = "."
tmp_dir = ".air-tmp"

[build]
  bin = "./.air-tmp/dbseer"
  cmd = "go build -tags dev -o ./.air-tmp/dbseer ./cmd/dbseer"
  delay = 200
  exclude_dir = ["web", "web/node_modules", "web/dist", ".git", ".motif", ".air-tmp", ".github"]
  include_ext = ["go"]
  stop_on_error = true
  args_bin = ["--dev"]

[log]
  time = true

[color]
  main = "magenta"
  build = "yellow"
  runner = "green"
